export type UserRole = "Admin" | "Asset Manager" | "Department Head" | "Employee";

export interface Organization {
  id: string;
  name: string;
  logoUrl?: string;
  industry?: string;
  size?: string;
  address?: string;
}

export interface User {
  id: string;
  email: string;
  phone?: string;
  fullName: string;
  role: UserRole;
  organizationId: string;
  departmentId?: string;
  status: "approved" | "pending_approval";
  createdAt: string;
}

export interface Department {
  id: string;
  name: string;
  headUserId?: string;
  parentDepartmentId?: string;
  status: "Active" | "Inactive";
}

export interface AssetCategory {
  id: string;
  name: string;
  warrantyPeriodMonths?: number;
  customFields?: string[];
}

export interface Asset {
  tag: string; // Autogenerated (e.g. AST-1001)
  name: string;
  categoryId: string;
  status: "Available" | "Allocated" | "Under Maintenance" | "Lost" | "Damaged";
  location: string;
  serialNumber: string;
  acquisitionDate: string;
  condition: "New" | "Good" | "Fair" | "Poor";
  imageUrl?: string;
}

export interface Allocation {
  id: string;
  assetTag: string;
  userId: string;
  assignedDate: string;
  expectedReturnDate: string;
  actualReturnDate?: string;
  status: "Active" | "Returned";
}

export interface TransferRequest {
  id: string;
  assetTag: string;
  fromUserId: string;
  toUserId: string;
  reason: string;
  status: "Pending" | "Approved" | "Rejected";
  createdAt: string;
}

export interface Resource {
  id: string;
  name: string;
  type: "Room" | "Vehicle" | "Equipment";
  requiresApproval: boolean;
}

export interface Booking {
  id: string;
  resourceId: string;
  userId: string;
  start: string; // ISO string
  end: string;   // ISO string
  status: "Pending Approval" | "Confirmed" | "Cancelled" | "Rejected";
  createdAt: string;
}

export interface MaintenanceRequest {
  id: string;
  assetTag: string;
  userId: string; // Raised by
  description: string;
  status: "Pending" | "Approved" | "Technician Assigned" | "In Progress" | "Resolved";
  assignedTech?: string;
  createdAt: string;
}

export interface AuditCycle {
  id: string;
  scope: string; // e.g. "IT Department" or "Main Office"
  startDate: string;
  endDate: string;
  status: "Active" | "Completed";
  auditorIds: string[];
  items: { [assetTag: string]: "Verified" | "Missing" | "Damaged" };
  closedAt?: string;
}

export interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: "alert" | "approval" | "booking" | "system";
  isRead: boolean;
  createdAt: string;
}

export interface ActivityLog {
  id: string;
  userId: string;
  fullName: string;
  role: UserRole;
  assetTag?: string;
  action: string;
  note: string;
  createdAt: string;
}
